#pragma once

#define INTERNAL_CAT(_1, _2) _1##_2

#define INTERNAL_IF_1(_Then, _Else) _Then
#define INTERNAL_IF_0(_Then, _Else) _Else

#define IS_ZERO_INTERNAL_0 1
#define IS_ZERO_INTERNAL_1 0
#define IS_ZERO_INTERNAL_2 0
#define IS_ZERO_INTERNAL_3 0
#define IS_ZERO_INTERNAL_4 0
#define IS_ZERO_INTERNAL_5 0
#define IS_ZERO_INTERNAL_6 0
#define IS_ZERO_INTERNAL_7 0
#define IS_ZERO_INTERNAL_8 0
#define IS_ZERO_INTERNAL_9 0
#define IS_ZERO_INTERNAL_10 0
#define IS_ZERO_INTERNAL_11 0
#define IS_ZERO_INTERNAL_12 0
#define IS_ZERO_INTERNAL_13 0
#define IS_ZERO_INTERNAL_14 0
#define IS_ZERO_INTERNAL_15 0
#define IS_ZERO_INTERNAL_16 0

#define INCREMENT_0 1
#define INCREMENT_1 2
#define INCREMENT_2 3
#define INCREMENT_3 4
#define INCREMENT_4 5
#define INCREMENT_5 6
#define INCREMENT_6 7
#define INCREMENT_7 8
#define INCREMENT_8 9
#define INCREMENT_9 10
#define INCREMENT_10 11
#define INCREMENT_11 12
#define INCREMENT_12 13
#define INCREMENT_13 14
#define INCREMENT_14 15
#define INCREMENT_15 16

#define DECREMENT_1 0
#define DECREMENT_2 1
#define DECREMENT_3 2
#define DECREMENT_4 3
#define DECREMENT_5 4
#define DECREMENT_6 5
#define DECREMENT_7 6
#define DECREMENT_8 7
#define DECREMENT_9 8
#define DECREMENT_10 9
#define DECREMENT_11 10
#define DECREMENT_12 11
#define DECREMENT_13 12
#define DECREMENT_14 13
#define DECREMENT_15 14
#define DECREMENT_16 15

#define INTERNAL_TUPLE_FIRST(first, ...) first
#define INTERNAL_TUPLE_REMOVE_FIRST(first, ...) __VA_ARGS__

#define INTERNAL_ITERATE_TUPLE_1(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \

#define INTERNAL_ITERATE_TUPLE_2(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_REMOVE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_3(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_2(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \

#define INTERNAL_ITERATE_TUPLE_4(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_3(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_5(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_4(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_6(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_5(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_7(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_6(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_8(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_7(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_9(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_8(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_10(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_9(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_11(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_10(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_12(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_11(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_13(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_12(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_14(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_13(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_15(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_14(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_ITERATE_TUPLE_16(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4) \
	INTERNAL_ITERATE_TUPLE_15(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4)

#define INTERNAL_NTH_ARG(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, _16, N, ...) N
#define INTERNAL_NUM(...) INTERNAL_CAT(INTERNAL_NTH_ARG(__VA_ARGS__, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1),)

#define INTERNAL_REVERSE_ITERATE_TUPLE_1(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_REMOVE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_2(Macro, tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_REMOVE_FIRST tuple, _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_3(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_2(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_4(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_3(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_5(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_4(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_6(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_5(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_7(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_6(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_8(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_7(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_9(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_8(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_10(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_9(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_11(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_10(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_12(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_11(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_13(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_12(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_14(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_13(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_15(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_14(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

#define INTERNAL_REVERSE_ITERATE_TUPLE_16(Macro, tuple, _1, _2, _3, _4) \
	INTERNAL_REVERSE_ITERATE_TUPLE_15(Macro, (INTERNAL_TUPLE_REMOVE_FIRST tuple), _1, _2, _3, _4) \
	CALL_MACRO(Macro, INTERNAL_TUPLE_FIRST tuple, _1, _2, _3, _4)

